# Generated by Django 4.1.3 on 2022-11-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title', 'content'], name='articles_ar_title_6ec69d_idx'),
        ),
    ]
