# Generated by Django 4.1.3 on 2022-11-24 09:36

from django.db import migrations


def create_new_articles(apps, scheme_migrations):
    Article = apps.get_model("articles", "Article")
    articles = []

    for number in range(1, 5):
        articles.append(Article(title=f"This is new {number} article",
                                content=f"Some content {number}",
                                cat_id=1,
                                user_id=1))

    Article.objects.bulk_create(articles)


def delete_articles(apps, scheme_migrations):
    Article = apps.get_model("articles", "Article")
    Article.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_articles_ar_title_6ec69d_idx'),
    ]

    operations = [
        migrations.RunPython(create_new_articles, delete_articles),
    ]
