# Generated by Django 4.1.3 on 2022-11-24 10:47

from django.db import migrations


def create_categories(apps, scheme_migrations):
    Caterogy = apps.get_model("articles", "Category")
    categories = []
    names = ("instruments", "cats", "dogs", "toys", "nature")

    for name in names:
        categories.append(Caterogy(name=name))

    Caterogy.objects.bulk_create(categories)


def delete_categories(apps, scheme_migrations):
    Caterogy = apps.get_model("articles", "Category")
    Caterogy.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_create_some_articles'),
    ]

    operations = [
        migrations.RunPython(create_categories, delete_categories),
    ]
