# Generated by Django 4.1.3 on 2022-11-24 11:45
from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.conf import settings


def create_user(apps, scheme_migrations):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    users = []
    names = ("Jack", "John", "Jane", "Don", "Ken")

    for name in names:
        users.append(User(
            email=f'{name}@user.com',
            password=make_password(name),
            username=f"{name}"
        ))

    User.objects.bulk_create(users)


def delete_user(apps, scheme_migrations):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    User.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_create_categories'),
    ]

    operations = [
        migrations.RunPython(create_user, delete_user),
    ]
